version: "3.8"
services:
  spring-boot-app:
    depends_on:
      postgresql:
        condition: service_healthy
    build: 
      context: .
      dockerfile: spring-boot-app.Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/demodb
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=demouser
      - SPRING_DATASOURCE_PASSWORD=DemoPa$$$$
      - APP_NODE_URL=http://node-app:8081/
    ports:
      - 8080:8080
    restart: unless-stopped
  node-app:
    build: 
      context: .
      dockerfile: node-app.Dockerfile
    ports:
      - 8081:8081
    restart: unless-stopped
  postgresql:
    image: postgres:10
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: demouser
      POSTGRES_PASSWORD: DemoPa$$$$
      POSTGRES_DB: demodb
    volumes:
      - db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db: